// <auto-generated />
using DatabaseTables.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseTables.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DatabaseTables.Models.Log", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Clicks");

                    b.HasKey("UserID");

                    b.ToTable("Clicks");
                });

            modelBuilder.Entity("DatabaseTables.Models.Sector", b =>
                {
                    b.Property<int>("SectorNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Status1");

                    b.Property<bool>("Status2");

                    b.Property<bool>("Status3");

                    b.Property<bool>("Status4");

                    b.Property<bool>("Status5");

                    b.Property<bool>("Status6");

                    b.Property<bool>("Status7");

                    b.Property<bool>("Status8");

                    b.Property<bool>("Status9");

                    b.HasKey("SectorNumber");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("DatabaseTables.Models.Temperature", b =>
                {
                    b.Property<int>("TempID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OneHour");

                    b.Property<int>("ThreeHours");

                    b.Property<int>("TwoHours");

                    b.Property<int>("fourHours");

                    b.HasKey("TempID");

                    b.ToTable("TemperatureValues");
                });

            modelBuilder.Entity("DatabaseTables.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
